services:
  fluent-bit-a:
    container_name: FB-A
    hostname: FB-A
    build: docker/fluent-bit/
    #restart: always
    volumes:
      - ./etc/fluent-docker:/etc/fluent-bit/
      - ./data/docker-fluent/:/var/data
      - ./bin/linux-amd64:/opt/fluent-bit/plugin/
    depends_on:
      - redis
    links:
      - redis            

  fluent-bit-b:
    container_name: FB-B
    hostname: FB-B
    build: docker/fluent-bit/
    #restart: always
    volumes:
      - ./etc/fluent-docker:/etc/fluent-bit/
      - ./data/docker-fluent/:/var/data
      - ./bin/linux-amd64:/opt/fluent-bit/plugin/
    depends_on:
      - redis
    links:
      - redis

  fluent-bit-c:
    container_name: FB-C
    hostname: FB-C
    build: docker/fluent-bit/
    #restart: always
    volumes:
      - ./etc/fluent-docker:/etc/fluent-bit/
      - ./data/docker-fluent/:/var/data
      - ./bin/linux-amd64:/opt/fluent-bit/plugin/
    depends_on:
      - redis
    links:
      - redis

  fluent-bit-d:
    container_name: FB-D
    hostname: FB-D
    build: docker/fluent-bit/
    #restart: always
    volumes:
      - ./etc/fluent-docker:/etc/fluent-bit/
      - ./data/docker-fluent/:/var/data
      - ./bin/linux-amd64:/opt/fluent-bit/plugin/
    depends_on:
      - redis
    links:
      - redis
