services:
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes    
    ports:
      - '6379:6379'
    volumes: 
      - ./data/docker-redis:/data
    depends_on:
      - localstack
      
  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4510-4559:4510-4559"
    environment:
      - SERVICES=s3,sts
  
  fluent-bit:
    image: cr.fluentbit.io/fluent/fluent-bit
    # restart: always
    volumes:
      - ./etc/fluent-docker:/fluent-bit/etc/
      - ./data/docker-fluent/:/var/data
      - ./bin/linux-amd64:/fluent-bit/plugin/
    depends_on:
      - redis
      - localstack
    links:
      - redis
      - localstack