FROM golang:1.20 as builder

WORKDIR /go/src/

RUN apt-get update && apt-get install -y gcc-aarch64-linux-gnu

ENV CGO_ENABLED=1 
ENV CC=aarch64-linux-gnu-gcc 
ENV GOOS=linux GOARCH=arm64

ENTRYPOINT [ "bash" ]